fix TypeError
Prior stacktrace:
```julia-repl
Error During Test at /Users/alec/.julia/dev/Miletus/test/montecarlo.jl:31
  Test threw exception
  Expression: isapprox(value(m, c), value(mcm, c), rtol = 0.01)
  TypeError: in CurrencyQuantity, in T, expected T<:Real, got Type{Number}
  Stacktrace:
    [1] promote_type(#unused#::Type{CurrencyQuantity{CurrencyUnit{:USD}, Float64}}, #unused#::Type{CurrencyQuantity{CurrencyUnit{:USD}, Float64}})
      @ Miletus.Currency ~/.julia/dev/Miletus/src/currency.jl:88
    [2] _mean_promote(x::CurrencyQuantity{CurrencyUnit{:USD}, Float64}, y::CurrencyQuantity{CurrencyUnit{:USD}, Float64})
      @ Statistics ~/.julia/juliaup/julia-1.8.0+0.aarch64/share/julia/stdlib/v1.8/Statistics/src/Statistics.jl:166
    [3] mean(f::typeof(identity), itr::Base.Generator{Miletus.ScenarioIterator{MonteCarloModel{CoreModel{CurrencyQuantity{CurrencyUnit{:USD}, Float64}, Miletus.TermStructure.ConstantContinuousYieldCurve{Actual365, Float64}, Miletus.TermStructure.ConstantContinuousYieldCurve{Actual365, Float64}}, StepRange{Date, Day}, CurrencyQuantity{CurrencyUnit{:USD}, Float64}}}, Miletus.var"#5#6"{Miletus.When{Miletus.LiftObs{typeof(==), Tuple{Miletus.DateObs, Miletus.ConstObs{Date}}, Bool}, SingleStock}, Int64}})
      @ Statistics ~/.julia/juliaup/julia-1.8.0+0.aarch64/share/julia/stdlib/v1.8/Statistics/src/Statistics.jl:74
    [4] mean
      @ ~/.julia/juliaup/julia-1.8.0+0.aarch64/share/julia/stdlib/v1.8/Statistics/src/Statistics.jl:44 [inlined]
    [5] value(m::MonteCarloModel{CoreModel{CurrencyQuantity{CurrencyUnit{:USD}, Float64}, Miletus.TermStructure.ConstantContinuousYieldCurve{Actual365, Float64}, Miletus.TermStructure.ConstantContinuousYieldCurve{Actual365, Float64}}, StepRange{Date, Day}, CurrencyQuantity{CurrencyUnit{:USD}, Float64}}, c::Miletus.When{Miletus.LiftObs{typeof(==), Tuple{Miletus.DateObs, Miletus.ConstObs{Date}}, Bool}, SingleStock})
      @ Miletus ~/.julia/dev/Miletus/src/models/montecarlo.jl:94
    [6] top-level scope
      @ ~/.julia/juliaup/julia-1.8.0+0.aarch64/share/julia/stdlib/v1.8/Test/src/Test.jl:464
    [7] include(fname::String)
      @ Base.MainInclude ./client.jl:476
    [8] top-level scope
      @ ~/.julia/dev/Miletus/test/runtests.jl:11
    [9] include(fname::String)
      @ Base.MainInclude ./client.jl:476
   [10] top-level scope
      @ none:6
   [11] eval
      @ ./boot.jl:368 [inlined]
   [12] exec_options(opts::Base.JLOptions)
      @ Base ./client.jl:276
   [13] _start()
      @ Base ./client.jl:522
ERROR: LoadError: There was an error during testing
in expression starting at /Users/alec/.julia/dev/Miletus/test/montecarlo.jl:31
in expression starting at /Users/alec/.julia/dev/Miletus/test/runtests.jl:11
ERROR: Package Miletus errored during testing
```